### ISSUE TITLE
DialogHMData.cs is missing

### ISSUE THREAD

**Issue by ManniAT** [roschinsky/HomeMatic-XmlApi-Lib#1]
Hi,

I checked the project an VS argues that (in Test) Dialo...CS is missing.
D...designer.cs and .resx are there

Could you pleas check in the missing file?

Thank you
Manfred

**Comment by roschinsky** [comment]
Hi Manfred,

yes sure! Sorry about that. It was excluded - no idea why. I put it (back?) in place, so now things shall run smoothly.

Thanks for the hint!
Thomas
